`define MODULE_NAME MIPI_DSI_CSI2_TX_Top
`define DSICSI2_TX_GEAR8
`define DSICSI2_TX_CSI
`define DSICSI2_TX_DATA_2_LANE
`define DSICSI2_TX_CRC_GEN
`define DSICSI2_TX_LPX_CN 5
`define DSICSI2_TX_HS_PREP_CN 4
`define DSICSI2_TX_HS_ZERO_CN 9
`define DSICSI2_TX_HS_TRAIL_CN 6
`define DSICSI2_TX_HS_EXIT_CN 9
